version: '3'

services: 
    gitlab: 
        image: soljsn/gitlab-all-in-one:0.2
        container_name: dev_gitlab
        environment: 
            # It's no working fot the image.
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://${SERVER_DOMAIN}/gitlab'
                registry_external_url 'http://${SERVER_DOMAIN}/registry'
                # letsencrypt['enable'] = false
                # Configure headers for outgoing email.
                gitlab_rails['gitlab_email_enabled'] = true
                gitlab_rails['gitlab_email_from'] = 'no-reply@${SERVER_DOMAIN}'
                gitlab_rails['gitlab_email_display_name'] = 'GitLab'
                gitlab_rails['gitlab_email_reply_to'] = 'no-reply@${SERVER_DOMAIN}'
                # Send outgoing email via the SMTP container:
                gitlab_rails['smtp_enable'] = true
                gitlab_rails['smtp_address'] = "mail"
                gitlab_rails['smtp_port'] = 25
                gitlab_rails['smtp_tls'] = false
                # Limit backup lifetime to 7 days (604800 seconds):
                gitlab_rails['backup_keep_time'] = 604800
        ports: 
            - '4080:80'
            - '4430:443'
            - '4022:22'
    
    redmine:
        image: soljsn/redmine-all-in-one:0.3
        container_name: dev_redmine
        ports:
            - '3080:80'
    
    # proxy:
    #     image: nginx-proxy:alpine
    #     container_name: proxy
